import base64

encrypted = "QXF1w60gZXN0w6FzLi4uIMKhSnVzdG8gYSB0aWVtcG8hIFRlIGhhYmxvIGRlc2RlIGVsIHBsYW5ldGEgUHl0aG9uIGRlbCB1bml2ZXJzbyA2MTYuCgpBbGdvIGV4dHJhw7FvIGVzdMOhIG9jdXJyaWVuZG8uLi4gwqFFbCBwbGFuZXRhIEphdmFTY3JpcHQgc2UgaGEgdnVlbHRvIGxvY28geSBxdWllcmUgYXJyZWJhdGFyIG51ZXN0cm8gbHVnYXIhIEFsIHBhcmVjZXIsIHR1IHVuaXZlcnNvIHkgZWwgbcOtbyBzZSBlc3TDoW4gZnVzaW9uYW5kbywgeSBzaSBubyBoYWNlbW9zIGFsZ28gYWhvcmEsIHRvZG8gcG9kcsOtYSBjb2xhcHNhci4KCk5lY2VzaXRhbW9zIHF1ZSBub3MgZW52w61lcyBsYSBmZWNoYSBkZSBsYSBwcmltYSB2ZXJzacOzbiBkZSBDb2RlbWJlci5kZXYsIHBlcm8gZGViZSBlc3RhciBlbiBtaWxpc2VndW5kb3MuIFVzYSBlbCB0aWVtcG8gMDA6MDAgZW4gVVRDLiDCoURlYmVyw61hIGZ1bmNpb25hciEgwqFFbiBlc3RlIHVuaXZlcnNvIHVzYW1vcyB1biBmb3JtYXRvIGRpZmVyZW50ZSBhbCBkZSB1c3RlZGVzISDCoURhdGUgcHJpc2EhCgpUYWwgdmV6LCBzaSBsb2dyYW1vcyBhbGluZWFyIGVsIHRpZW1wbywgcG9kcmVtb3MgdGVuZXIgdW5hIG9wb3J0dW5pZGFkLiBQdWVkZXMgZW52aWFybG8gYXF1w606IGh0dHBzOi8vY29kZW1iZXIuZGV2L2FwaS9tdWx0aXZlcnNlLWNoYW5uZWwuanNvbj90aW1lPVt5b3VyX3RpbWVfbXNdCgrCoVLDoXBpZG8sIGVsIHRpZW1wbyBjb3JyZSBlbiBudWVzdHJhIGNvbnRyYSE="
new_message = "oUdyYWNpYXMgcG9yIGF5dWRhcm5vcyEgRGVzZGUgZWwgdW5pdmVyc28gQ2VybywgdGUgZGViZW1vcyB1bmEgOik="


def decrypt(message):
    return base64.b64decode(message).decode("utf-8")


open("message.txt", "x").write(decrypt(encrypted))
open("new_message.txt", "x").write(decrypt(new_message))
